### ISSUE TITLE
Scraper with SSL error

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/coffs_harbour#4]
```
/app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
 	from /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
 	from /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
 	from /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
 	from /app/vendor/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:882:in `start'
 	from /app/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
 	from /app/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
 	from /app/vendor/bundle/ruby/2.4.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
 	from /app/vendor/bundle/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'
 	from /app/vendor/bundle/ruby/2.4.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
 	from scraper.rb:21:in `<main>'
```

**Comment by LoveMyData** [comment]
Council updated its web site certificate and ruby doesn't have the latest authority on record, hence erroring.
